# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Country_ID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Country_name', models.CharField(max_length=20)),
                ('Country_code', models.CharField(default='Country_code', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Country_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreFriends', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('Language_ID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rank_translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Content', models.TextField()),
                ('Sentence_tag', models.TextField(default='unknown')),
                ('Likes', models.PositiveIntegerField(default=0)),
                ('Views', models.PositiveIntegerField(default=0)),
                ('Translation_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('TopicID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Topic_tag', models.TextField(default='unknown')),
                ('Link', models.TextField(default='unknown')),
                ('Likes', models.PositiveIntegerField(default=0)),
                ('Views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('TID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Content', models.TextField()),
                ('Translation_tag', models.TextField(default='unknown')),
                ('Likes', models.PositiveIntegerField(default=0)),
                ('Views', models.PositiveIntegerField(default=0)),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Sentence')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('SocialID', models.BigIntegerField(null=True, unique=True)),
                ('UserIcon', models.ImageField(default='/static/images/fish.png', upload_to='/static/UserIcon_folder')),
                ('NativeLanguage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Language')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.User')),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.User'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='TopicID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sentence.Topic'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.User'),
        ),
        migrations.AddField(
            model_name='rank_translation',
            name='TID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Translation'),
        ),
        migrations.AddField(
            model_name='rank_translation',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.User'),
        ),
        migrations.AddField(
            model_name='rank_sentence',
            name='SID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Sentence'),
        ),
        migrations.AddField(
            model_name='rank_sentence',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.User'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='Friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='sentence.User'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.User'),
        ),
        migrations.AddField(
            model_name='country_language',
            name='Language_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Language'),
        ),
        migrations.AddField(
            model_name='collection',
            name='SID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Sentence'),
        ),
        migrations.AddField(
            model_name='collection',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.User'),
        ),
    ]
