# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('UserName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('UserIcon', models.ImageField(height_field=700, upload_to='UserIcon_folder', width_field=700)),
                ('EXP', models.IntegerField()),
                ('Money', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
    ]
