# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='UID2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='sentence.User'),
            preserve_default=False,
        ),
    ]
