# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0002_friendship_uid2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='UID2',
            new_name='Friend',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='UID1',
            new_name='UID',
        ),
    ]
