# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0002_remove_user_nativelanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NativeLanguage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sentence.Language'),
            preserve_default=False,
        ),
    ]
