# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0002_auto_20170409_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='NativeLanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Language'),
        ),
    ]
