# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0002_remove_user_usericon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='EXP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Money',
        ),
    ]
