# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0003_auto_20170108_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserIcon',
            field=models.ImageField(default='/static/images/fish.png', upload_to='UserIcon_folder'),
        ),
    ]
