# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0003_auto_20161219_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
