# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0003_user_nativelanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserIcon',
            field=models.ImageField(default='/static/images/fish.png', upload_to='/static/images'),
        ),
    ]
