# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0006_auto_20161229_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='SocialID',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
