# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0008_auto_20161229_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='SID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
