# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 07:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0009_auto_20161229_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 30, 7, 36, 33, 857000, tzinfo=utc)),
        ),
    ]
