# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0012_auto_20161230_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime),
        ),
    ]
