# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0013_auto_20161230_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='Date',
            field=models.DateTimeField(blank=True),
        ),
    ]
