# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0020_auto_20161230_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('TID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Content', models.TextField()),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Sentence')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.User')),
            ],
        ),
    ]
