# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0021_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='Translation_tag',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='Sentence_tag',
            field=models.TextField(default='unknown'),
        ),
    ]
