# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0025_auto_20170102_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Country_ID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Country_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('Language_ID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Language', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='country_language',
            name='Language_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentence.Language'),
        ),
    ]
