# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0026_auto_20170102_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserIcon',
            field=models.ImageField(default='static\\images\x0cish.png', height_field=700, upload_to='UserIcon_folder', width_field=700),
        ),
    ]
