# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0027_user_usericon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserIcon',
            field=models.ImageField(default='static/images/fish.png', height_field=700, upload_to='UserIcon_folder', width_field=700),
        ),
    ]
