# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0033_auto_20170103_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sentence.Language'),
            preserve_default=False,
        ),
    ]
