# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0034_user_language_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_ID',
        ),
    ]
