# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0035_remove_user_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='Views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='Views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translation',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translation',
            name='Views',
            field=models.BigIntegerField(default=0),
        ),
    ]
