# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0036_auto_20170105_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='Likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='Views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='translation',
            name='Likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='translation',
            name='Views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
