# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0039_remove_user_language_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='Likes',
        ),
    ]
