# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0038_remove_user_usericon'),
        ('sentence', '0041_sentence_likes'),
    ]

    operations = [
    ]
