# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0042_merge_20170105_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserIcon',
            field=models.ImageField(default='/images/fish.png', upload_to='UserIcon_folder'),
        ),
    ]
