# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0043_user_usericon'),
        ('sentence', '0039_user_usericon'),
    ]

    operations = [
    ]
