# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0045_auto_20170106_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={},
        ),
    ]
