# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0040_country_country_code'),
        ('sentence', '0046_auto_20170106_1546'),
    ]

    operations = [
    ]
