# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0047_merge_20170106_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='Country_code',
        ),
    ]
