# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0047_collection'),
        ('sentence', '0048_remove_country_country_code'),
    ]

    operations = [
    ]
