# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0049_merge_20170106_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='Country_code',
            field=models.CharField(default='Country_code', max_length=5),
        ),
    ]
