# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0050_country_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='Likes',
        ),
    ]
