# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0051_remove_collection_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='SID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sentence.Sentence'),
            preserve_default=False,
        ),
    ]
