# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0051_remove_sentence_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='Likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
