# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0052_collection_sid'),
        ('sentence', '0052_sentence_likes'),
    ]

    operations = [
    ]
